# Generated by Django 3.0.2 on 2020-03-21 10:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.CharField(max_length=32, unique=True)),
                ('guid', models.CharField(blank=True, default='No GUID', max_length=10, null=True)),
                ('topic_discussed', models.CharField(default='student conversation', max_length=50)),
                ('conversation_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='date published')),
                ('log', models.CharField(max_length=50000, null=True)),
                ('slug', models.SlugField(default='log', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('file', models.FileField(upload_to='resources')),
                ('slug', models.SlugField(default='resource', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_users', models.BooleanField(default=False)),
                ('manage_logs', models.BooleanField(default=False)),
                ('manage_resources', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
